services:
  rabbit_hole:
    image: rabbit-hole-node:20240824
    build:
        context: .
        dockerfile_inline: |
          FROM node:20.10.0
          # Install networking utilities
          RUN apt-get update && \
              apt-get install -y iputils-ping netcat-openbsd && \
              apt-get clean && \
              rm -rf /var/lib/apt/lists/*
          WORKDIR /app
          COPY package.json package-lock.json /app/
          RUN npm ci
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./dropped-messages:/app/dropped-messages
      - ./secrets:/app/secrets
    environment:
      - NODE_ENV=production
    command: |
      node /app/src/index.mjs \
        --prefetch-size 1000 \
        --env-file /app/secrets/docker.env \
        --queue-config /app/config/queue-conf-example.json5 \
        --runMode interval \
        --runSchedule="* * * * *" \
        --runDurationSeconds=300 \
        --v --v